[package]
name = "ecs-provisioner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.56.0"
aws-sdk-ecs = "0.29.0"
tokio = {version = "1.32.0", features=["full"]}
